name: 'stock_elt_project'
version: '1.0'
profile: 'dbt'

# dbt now uses 'model-paths' instead of 'source-paths'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to clean with `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring model materializations
models:
  stock_elt_project:
    +materialized: view

    intermediate:
      +materialized: ephemeral

    output:
      +materialized: table





      