name: 'Lab2_dbt_Folder'
version: '1.0.0'
profile: 'lab2_profile'  # <- make sure this matches your `profiles.yml`

# File path configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to clean with `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring model materializations
models:
  Lab2_dbt_Folder:  # <- This must match the `name` above
    +materialized: view  # default materialization for all models
    intermediate:
      +materialized: ephemeral  # override for staging models
    output:
      +materialized: table      # override for final reporting models